version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user_auth_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_auth_board
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: